WEB SCRAPING DOES NOT WORK. you can pull the data using share and more option and picking csv in bb-reference

In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the advanced stats page
url = 'https://www.basketball-reference.com/leagues/NBA_2025_advanced.html'

# Fetch the content from the URL
response = requests.get(url)
content = response.content

# Parse the HTML content
soup = BeautifulSoup(content, 'html.parser')

# Find the table containing advanced stats
body = soup.find('body', {'class': 'bbr'})
wrap = body.find('div', {'id': 'wrap'})
content = wrap.find('div', {'id': 'content', 'role': 'main'})

all_advanced_team = content.find('div', { 'id': 'all_advanced_team', 'class': 'table_wrapper'})
div_advanced_team = all_advanced_team.find('div', {'id': 'div_advanced-team'})
table = div_advanced_team.find('table', {'class': 'stats_table sortable now_sortable is_sorted', 'id': 'advanced_stats'})

headers = table.find('thead').find_all('th')
headers = [ele.text.strip() for ele in headers]


rows = table.find('tbody').find_all('tr')
data = []
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele])




# Create a DataFrame
advanced_stats_df = pd.DataFrame(rows, columns=headers[1:])  # Skip the first header as it is the index

# Save the DataFrame to a CSV file
advanced_stats_df.to_csv('advanced_stats_nba_2025.csv', index=False)

AttributeError: 'NoneType' object has no attribute 'find'

In [ ]:
nba_general = pd.read_csv('bb_reference.csv') 

nba_general.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Offense Four Factors.3,Unnamed: 22,Defense Four Factors,Defense Four Factors.1,Defense Four Factors.2,Defense Four Factors.3,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Rk,Team,Age,W,L,PW,PL,MOV,SOS,SRS,...,FT/FGA,NaN,eFG%,TOV%,DRB%,FT/FGA,NaN,Arena,Attend.â–¼,Attend./G
1,1,Cleveland Cavaliers,26.7,48,10,47,11,11.67,-0.97,10.71,...,.183,NaN,.526,12.9,75.5,.180,NaN,Rocket Arena,602392,19432
2,2,Toronto Raptors,24.7,18,40,19,39,-5.66,1.59,-4.07,...,.177,NaN,.546,12.7,73.6,.225,NaN,Scotiabank Arena,598279,18696
3,3,Philadelphia 76ers,28.2,20,37,21,36,-4.56,-0.03,-4.59,...,.210,NaN,.568,15.0,73.1,.203,NaN,Wells Fargo Center,595208,19840
4,4,Chicago Bulls,25.4,23,35,22,36,-4.00,-0.23,-4.23,...,.168,NaN,.542,10.7,76.2,.179,NaN,United Center,594590,19820

In [ ]:
ny_knicks = pd.read_csv('ny_knicks_24-25.csv')

ny_knicks.head()

,Unnamed: 0,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Team,57.0,13780,2509,5091,0.493,728,1946,0.374,1781,...,0.805,615,1833,2448,1565,452,216,749,965,6718
1,Team/G,NaN,241.8,44.0,89.3,0.493,12.8,34.1,0.374,31.2,...,0.805,10.8,32.2,42.9,27.5,7.9,3.8,13.1,16.9,117.9
2,Lg Rank,NaN,18,5,17,3.000,19,27,6.000,2,...,5.000,20,25,24,11,16,29,3,5,5
3,Year/Year,NaN,0.5%,6.6%,0.7%,0.027,-3.3%,-4.6%,0.005,11.3%,...,0.025,-14.8%,-1.1%,-4.9%,12.7%,6.2%,-7.5%,-0.7%,-4.1%,4.5%
4,Opponent,57.0,13780,2396,5049,0.475,786,2062,0.381,1610,...,0.795,619,1755,2374,1486,399,283,805,1093,6445